/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#if !defined __GSKEYMAIN__H
#define __GSKEYMAIN__H

#include <gtk/gtk.h>

typedef struct {
  GtkWidget *window;
  GtkWidget *entrySeed, *entryPassword, *spinNumber, *entryMD5String;
} GSkeyWidgets;

GSkeyWidgets *GSkey_create (void);

#endif
